<?php

return [
    'HC01' => [
        'name'     => '(1-HC)-การฟอกโลหิตหรือการล้างไตทางช่องท้อง',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC011' => [
        'name'     => '(1-HC)-การฟอกโลหิต',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC012' => [
        'name'     => '(1-HC)-การล้างไตทางช่องท้อง',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC02' => [
        'name'     => '(1-HC)-การให้เคมีบาบัดและหรือรังสีรักษาในผู้ป่วยโรคมะเร็ง',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC03' => [
        'name'     => '(1-HC)-CA BREAST',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC04' => [
        'name'     => '(1-HC)-ค่ายาในการรักษาผู้ป่วยเยื่อหุ้มสมองอักเสบจากเชื อรา',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC05' => [
        'name'     => '(1-HC)-CMV RETINITIS',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC051' => [
        'name'     => '(1-HC)-CMV RETINITIS 1 สัปดาห์',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC052' => [
        'name'     => '(1-HC)-CMV RETINITIS 2 สัปดาห์',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC06' => [
        'name'     => '(1-HC)-การตรวจวิฉัยราคาแพงและหัตถการโรคหัวใจ(OP HEART)',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC07' => [
        'name'     => '(1-HC)-การให้สารเมทาโดนในผู้ติดสารเสพติด',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HC08' => [
        'name'     => '(1-HC)-การรักษาด้วย ออกซิเจนความกดดันสูง',
        'category' => 'HC (OPD)',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
];
