<?php

return [
    'ADSCOV' => [
        'name'     => '(5-Project code)-สิทธิ UC ผู้ป่วยในที่เข้าเกณฑ์คัดกรองโควิด 19',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 19.00,
            'OFC'  => 19.00,
            'SSS'  => 19.00,
            'LGO'  => 19.00,
            'FS'  => 19.00,
            'UCEP'  => 19.00,
        ],
    ],
    'AF72AE' => [
        'name'     => '(5-Project code)-เบิกค่ารักษาหลัง 72 ชั่วโมง',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'ART7RF' => [
        'name'     => '(5-Project code)-การขอรับค่าใช้จ่ายกรณีเหตุสมควร(มาตรา7)',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'BF72AE' => [
        'name'     => '(5-Project code)-เบิกค่ารักษาภายใน 72 ชั่วโมง',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'CANCER' => [
        'name'     => '(5-Project code)-มะเร็งรับบริการได้ทุกที่ที่พร้อม',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'DMISHD' => [
        'name'     => '(5-Project code)-การเบิกSHUNT ในผู้ป่วยฟอกเลือด(HD)',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'DMISRC' => [
        'name'     => '(5-Project code)-นิ่วในระบบทางเดินปัสสาวะ',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'DMLL54' => [
        'name'     => '(5-Project code)-มะเร็งเม็ดเลือดขาวและต่อมน้ำเหลือง',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'DMLP54' => [
        'name'     => '(5-Project code)-มะเร็งเม็ดเลือดขาว (เฉียบพลัน)',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'ER-EXT' => [
        'name'     => '(5-Project code) ฉุกเฉินคุณภาพ',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'GPOM17' => [
        'name'     => '(5-Project code)-ผ่าตัดข้อเข่าเทียม',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HD3995' => [
        'name'     => '(5-Project code)-เบิกส่วนต่างกรณีทำ HD',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'HOSPIC' => [
        'name'     => '(5-Project code)-การพักรอจำหน่าย',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'INJDTO' => [
        'name'     => '(5-Project code)-กรณีเจ็บป่วยจากการปฏิบัติราชการ',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'KNEE17' => [
        'name'     => '(5-Project code)-กรณีผ่าตัดข้อเข่าเทียม ที่หน่วยบริการต้องการเบิกข้อเข่าจากระบบปกติ',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'KTLGOD' => [
        'name'     => '(5-Project code)-การเบิกกรณีเป็นผู้ป่วยบริจาคไต',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'R9OPCH' => [
        'name'     => '(5-Project code)-ผู้ป่วยนอกรับบริการในจังหวัด เขต 9 นครราชสีมา',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'R9OPFS' => [
        'name'     => '(5-Project code)-ผู้ป่วยนอกรับบริการกรณีเหตุสมควร เขต 9 นครราชสีมา',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'SCRCOV' => [
        'name'     => '(5-Project code)-การตรวจคัดกรองและตรวจทางห้องปฏิบัติการโควิด 19',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 19.00,
            'OFC'  => 19.00,
            'SSS'  => 19.00,
            'LGO'  => 19.00,
            'FS'  => 19.00,
            'UCEP'  => 19.00,
        ],
    ],
    'SSAE72' => [
        'name'     => '(5-Project code)-กรณีรักษาฉุกเฉิน > 72 ชั่วโมง  และมีการรับไปรักษาต่อ',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'SSSOBS' => [
        'name'     => '(5-Project code)-การเบิกส่วนต่างจากสิทธิข้าราชการ',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'SSSSPC' => [
        'name'     => '(5-Project code)-การเบิกส่วนต่างประกันสังคม 5 กรณี',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'UCEP24' => [
        'name'     => '(5-Project code) UCEP 24 ชั่วโมงแรก',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 24.00,
        ],
    ],
    'WALKIN' => [
        'name'     => '(5-Project code) การเข้ารับบริการผู้ป่วยนอก ปฐมภูมิกรณีเหตุสมควร',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'X00000' => [
        'name'     => '(5-Project code)-อัคคีภัย',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'X38000' => [
        'name'     => '(5-Project code)-อุทกภัยน้ำท่วม',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'Z34003' => [
        'name'     => '(5-Project code)-ประกันสังคมส่งเงินสมทบไม่ครบ 3 เดือน',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'Z34007' => [
        'name'     => '(5-Project code)-ประกันสังคมส่งเงินสมทบไม่ครบ 7 เดือน',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'Z38000' => [
        'name'     => '(5-Project code)-เด็กแรกเกิดสิทธิข้าราชการ/อปท.',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'Z39000' => [
        'name'     => '(5-Project code)-เด็กแรกเกิดเสียชิวิตก่อนขึ้นทะเบียน',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'Z51158' => [
        'name'     => '(5-Project code)-การ Drip ยา',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'Z75000' => [
        'name'     => '(5-Project code)-ผู้ป่วยสิทธิว่างเสียชิวิตก่อนขึ้นทะเบียน',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
    'Z75REF' => [
        'name'     => '(5-Project code)-ศูนย์สำรองเตียง',
        'category' => 'Project code',
        'prices'   => [
            'UCS'  => 0.00,
            'OFC'  => 0.00,
            'SSS'  => 0.00,
            'LGO'  => 0.00,
            'FS'  => 0.00,
            'UCEP'  => 0.00,
        ],
    ],
];
