<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Rep_lgo extends Model
{
    use HasFactory;

    protected $table = 'rep_lgo';
    protected $primaryKey = 'id';
    
    protected $fillable = [
        'id',
        'rep_filename',
        'rep_type',
        'is_appeal',
        'repno',
        'no',
        'tran_id',
        'hn',
        'an',
        'cid',
        'pt_name',
        'pt_type',
        'datetimeadm',
        'vstdate',
        'vsttime',
        'datetimedch',
        'dchdate',
        'dchtime',
        'net_compensate_nhso',
        'net_compensate_employer',
        'compensate_from',
        'error_code',
        'main_fund',
        'sub_fund',
        'service_type',
        'refer_type',
        'has_right',
        'use_right',
        'chk',
        'maininscl',
        'subinscl',
        'href',
        'hcode',
        'hmain',
        'prov1',
        'rg1',
        'hmain2',
        'prov2',
        'rg2',
        'dmis_hmain3',
        'da',
        'proj',
        'pa',
        'drg',
        'rw',
        'ca_type',
        'charge_non_vehicle_drug_device',
        'charge_vehicle_drug_device',
        'charge_total',
        'charge_central_reimburse',
        'self_pay',
        'payrate_point',
        'delay_ps',
        'delay_percent',
        'ccuf',
        'adjrw_nhso',
        'adjrw2',
        'compensate_amount',
        'act_amount',
        'salary_percent',
        'salary_amount',
        'compensate_after_salary',
        'hc_iphc',
        'hc_ophc',
        'ae_opae',
        'ae_ipnb',
        'ae_ipuc',
        'ae_ip3sss',
        'ae_ip7sss',
        'ae_carae',
        'ae_caref',
        'ae_caref_puc',
        'inst_opinst',
        'inst_ipinst',
        'ip_ipaec',
        'ip_ipaer',
        'ip_ipinrgc',
        'ip_ipinrgr',
        'ip_ipinspsn',
        'ip_ipprcc',
        'ip_ipprcc_puc',
        'ip_ipbkk_inst',
        'ip_ip_ontop',
        'dmis_cataract',
        'dmis_ssj_workload',
        'dmis_hosp_workload',
        'dmis_catinst',
        'dmis_rc',
        'dmis_rc_workload',
        'dmis_rcuhosc',
        'dmis_rcuhosc_workload',
        'dmis_rcuhosr',
        'dmis_rcuhosr_workload',
        'dmis_llop',
        'dmis_llrgc',
        'dmis_llrgr',
        'dmis_lp',
        'dmis_stroke_stemi_drug',
        'dmis_dmidml',
        'dmis_pp',
        'dmis_dmishd',
        'dmis_dmicnt',
        'dmis_palliative_care',
        'dmis_dm',
        'drug',
        'opbkk_hc',
        'opbkk_dent',
        'opbkk_drug',
        'opbkk_fs',
        'opbkk_others',
        'opbkk_hsub',
        'opbkk_nhso',
        'deny_hc',
        'deny_ae',
        'deny_inst',
        'deny_ip',
        'deny_dmis',
        'base_rate_old',
        'base_rate_add',
        'base_rate_net',
        'fs',
        'va',
        'remark',
        'audit_results',
        'pay_pattern',
        'seq_no',
        'invoice_no',
        'invoice_lt',
    ];

    public $timestamps = false;
}
